Remove network calls
CCI-MOC/m2 pull request #166
Opened 2018-04-04 19:58 UTC by naved001

2018-06-22 22:36 UTC, naved001 commented
This one is next on my agenda.

2018-06-28 20:15 UTC, naved001 commented
@apoorvemohan @Izhmash @mihirborkar 
Let's start reviewing this. I am gonna push a few more commits to this one (or maybe separate PRs if they are unrelated) that will trim down some fat from the BMI code, and then I'll rewrite/split the provision and deprovision call.

2018-07-06 14:19 UTC, Izhmash commented
This looks good to me so far. Are you still planning to push more code here?

Also, as an aside, how close does this get us to decoupling HIL with M2? I think now the only things that M2 uses HIL for are authentication and reading network/node information.

2018-07-06 15:07 UTC, naved001 commented
I finished working on this. This only removes the network calls.

I'll removed the call to get Mac information later, and then auth will be the only thing left.

@apoorvemohan can I get another review on this?

2018-07-18 15:44 UTC, mihirborkar approved these changes
LGTM!!! 👍👍

2018-07-18 17:54 UTC, Izhmash commented
I think it looks good, what about the docs?

2018-07-27 15:40 UTC, naved001 commented
While updating the docs, I realized that there's no need to pass the nic for deprovisioning anymore (at least in the current implementation).

There are 2 uses of passing the nic I can think of:
1. To disconnect the network from (which won't be needed anymore).
2. To delete the boot configuration file which is named after the mac address. It looks like this:
```
DEFAULT menu
  PROMPT 0
  MENU TITLE PXE Menu
  ONTIMEOUT ubuntu-test


LABEL ubunutu-test
     MENU LABEL ubuntu-image
     KERNEL ipxe.lkrn
     INITRD dell-9.ipxe
```
Right now we don't do 2; does it make sense to do it now? We can either delete the ipxe file, or the boot configuration file or both. @apoorvemohan what do you think?

2018-07-27 18:51 UTC, naved001 commented
I am gonna leave the nic here as is so that this PR is easier to review. I am gonna make use of nic in deprovisioning later (to delete the boot configuration

2018-07-27 19:07 UTC, naved001 commented
@Izhmash updated the docs

2018-07-27 20:35 UTC, ianballou approved these changes
I think this looks fine, what's with the CI?

2018-08-01 18:07 UTC, apoorvemohan commented on ims/cli/cli.py
> +    NIC     = The NIC to use for Network Boot
why pass nic anymore? this is anyways hardcoded

2018-08-01 18:08 UTC, apoorvemohan commented on ims/cli/cli.py
> +def deprovision(project, node, nic):
again, why do we need nic?

2018-08-01 18:10 UTC, apoorvemohan commented on ims/einstein/operations.py
> +    def provision(self, node_name, img_name, nic):
why nic?

2018-08-01 18:11 UTC, apoorvemohan commented on ims/einstein/operations.py
> +    def provision(self, node_name, img_name, nic):
in bmi-config.cfg we can pass it - anyways the nic used for provisioning is different from nic name in HIL

2018-08-01 18:13 UTC, apoorvemohan commented on ims/picasso/rest.py
> +            constants.NIC_PARAMETER])
lets remove nic?

2018-08-01 18:13 UTC, apoorvemohan commented on ims/picasso/rest.py
> +           [constants.NODE_NAME_PARAMETER, constants.NIC_PARAMETER])
lets remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        response = self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        response = self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:14 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:15 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:15 UTC, apoorvemohan commented on tests/integration/einstein/test_operations.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:15 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:15 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:15 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:16 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 18:16 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.provision(NODE_NAME, EXIST_IMG_NAME, NIC)
remove nic?

2018-08-01 18:16 UTC, apoorvemohan commented on tests/unit/picasso/test_rest.py
> +        self.good_bmi.deprovision(NODE_NAME, NIC)
remove nic?

2018-08-01 19:19 UTC, ianballou requested changes
I'm gonna retract the +1 till we figure out the DB issues here: #174 

Edit: still not certain that this PR is the cause, but it's good to be safe

2018-08-02 15:25 UTC, naved001 commented
The CI was passing for this PR earlier, and now something else seems to be failing (some compilation error).

2018-08-06 20:25 UTC, naved001 commented
@ianballou  fixed the CI.

2018-08-07 15:58 UTC, ianballou commented
@naved001 were you able to test that added images also get related to the project?  I was worried that might've slipped through the CI somehow. If that's all good, then I'm cool with this.

2018-08-07 20:09 UTC, ianballou approved these changes

2018-08-07 21:22 UTC, naved001 commented
@apoorvemohan I can remove the nic from the dpro call if you want, but I will add it back again in the other PR for cleanup (to delete the boot configuration file).

2018-08-09 22:42 UTC, apoorvemohan approved these changes

2018-08-10 14:47 UTC, merged