Catch a bunch of errors everywhere:
CCI-MOC/m2 pull request #170
Opened 2018-06-22 22:35 UTC by naved001

This PR is pretty much copy-pasta from @chemistry-sourabh's #111 PR
since dealing with the merge conflicts was nasty and it made some changes
which I now feel are not necessary.

This has some fixes for database issues, ceph image issues, and tgt targets. And it's weird that we have to catch integrity errors, the code should be such that it's never even raised (I'll look fix that within this PR or maybe a different one).

I will add some integration tests too.

@apoorvemohan @mihirborkar @izhmash

2018-07-23 15:47 UTC, Izhmash commented on ims/einstein/iscsi/tgt.py
> +                os.remove(os.path.join(self.TGT_ISCSI_CONFIG,
Why did you have to move this command?

2018-08-20 14:30 UTC, ianballou approved these changes
I think this looks cool

2018-08-20 14:36 UTC, naved001 commented
Thanks for the review, but I think this will require more work once #174 is merged since that restructures a lot of things.

2018-08-21 14:55 UTC, jeremyfreudberg requested changes

2018-08-21 14:55 UTC, jeremyfreudberg commented on ims/einstein/ceph.py
> +        return true
welll, that's something

2018-08-21 14:55 UTC, jeremyfreudberg commented on ims/einstein/iscsi/tgt.py
> +            if "[Errno 2] No such file or directory" in str(e):
you should probably compare the value of `e.errno` to `2`, or for bonus points, compare it to `os.ENOENT`

2018-08-22 16:03 UTC, naved001 commented on ims/einstein/ceph.py
> +        return true
oops

2018-10-04 17:35 UTC, ianballou commented
How's this code looking now with the recent changes? Is everything still relevant?

2021-09-17 14:00 UTC, closed without merging